name: "Home Assistant Add-on: n8n"
version: 1.0.190.0.0
slug: hass-n8n-dev
description: "Host an n8n instance on your Home Assistant server (development version)"
url: https://github.com/vchkhr/hass-n8n-dev
codenotary: codenotary@frenck.dev
webui: "[PROTO:ssl]://[HOST]:[PORT:5678]"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  5678/tcp: 5678
ports_description:
  5678/tcp: "n8n Web Interface"
map:
  - ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  request_size_limit: int?
